name: freader_media_player
description: freader_media_player(FMP Player)，一个简单的本地媒体播放器，用于播放本地音频，浏览本地图片，观看本地视频。
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.2.2-beta+1

environment:
    sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # flutter 屏幕适配方案，用于调整屏幕和字体大小的flutter插件，让你的UI在不同尺寸的屏幕上都能显示合理的布局!
  flutter_screenutil: ^5.9.0
  # 国际化（多国语言）
  flutter_localizations:
    sdk: flutter
  # 用于从设备存储中查询音频/歌曲信息[标题、艺术家、专辑等]。
  on_audio_query: ^2.9.0
  # 音乐播放组件
  just_audio: ^0.9.36
  # 配合上一个实现后台播放(其他高级音频背景播放，使用audio_service)
  just_audio_background: ^0.0.1-beta.11
  # 同上配合使用，此插件会告知操作系统您的音频应用程序的性质（例如游戏、媒体播放器、助手等）以及您的应用程序将如何处理和启动音频中断（例如电话中断）
  audio_session: ^0.1.18
  # RxDart 扩展了 Dart Streams和 StreamControllers的功能 。
  rxdart: ^0.27.7
  # GetIt是一个简单的直接服务定位器，允许将接口与具体实现分离，并从应用程序的任何地方访问具体实现(一个单例的工具箱)。
  get_it: ^7.6.6
  # InheritedWidget的包装器 ，使它们更易于使用和可重用。（子孙传值、简单应用状态管理之类的）
  provider: ^6.1.1
  # 国际化，时间格式化等工具类
  intl: ^0.18.1
  # 文本跑马灯滚动
  marquee: ^2.2.3
  # 权限请求管理
  permission_handler: ^11.1.0
  # 文件系统中获取用户可用的地址
  path_provider: ^2.1.2
  # 包含用于在不同数据表示之间进行转换的编码器和解码器。dart:convert的补充
  convert: ^3.1.1
  # 加密库
  crypto: ^3.0.3
  # 音频播放
  video_player: ^2.8.2
  # video player包装器，更方便使用
  flick_video_player: ^0.7.0
  # 包装现有组件检测可见性
  visibility_detector: ^0.4.0+2
  # 一个插件，提供资产抽象管理API，无需UI集成，可以在Android、iOS和macOS上获取asset（图像/视频/音频）。
  # 2024-01-08 要使用开发版本，否则出现Type 'DecoderCallback' not found.问题而无法编译
  photo_manager: ^3.0.0-dev.5
  # 2024-01-08 原本使用的AssetEntityImage 类变成这个单独的包了
  photo_manager_image_provider: ^2.1.0
  # 图片预览操作等
  photo_view: ^0.14.0
  # shared_preferences持久话可能会丢失，使用这个代替
  get_storage: ^2.1.1
  # 获取设备信息，比如Android版本之类的
  # 2024-01-12(9.x和flick_video_player0.7.0有冲突)
  device_info_plus: ^8.2.2
  # 提供了操作路径(path)的常用操作：连接、分割、规范化等。
  path: ^1.8.3
  # 调整应用内亮度
  screen_brightness: ^0.2.2+1
  # 调整系统音量
  flutter_volume_controller: ^1.3.1
  ### 2024-01-26新加：2048 需要的一些库
  # 状态管理(TODO 其实已经有 provider了，后续可以考虑复用)
  flutter_riverpod: ^2.4.9
  uuid: ^4.3.3
  # 滑动检测(TODO 这个包有点老了，可以后续找找替代品)
  flutter_swipe_detector: ^2.0.0 
  ### 2024-01-29新加：俄罗斯方块需要的一些库
  soundpool: ^2.4.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/launch_background.png
    - assets/games/
    - assets/games/tetris/
    - assets/games/tetris/audios/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
